// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v2

import (
	unsafe "unsafe"

	v1beta1 "github.com/rabbitmq/cluster-operator/api/v1beta1"
	status "github.com/rabbitmq/cluster-operator/internal/status"
	appsv1 "k8s.io/api/apps/v1"
	v1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClientService)(nil), (*v1beta1.ClientService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_ClientService_To_v1beta1_ClientService(a.(*ClientService), b.(*v1beta1.ClientService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClientService)(nil), (*ClientService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClientService_To_v2_ClientService(a.(*v1beta1.ClientService), b.(*ClientService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EmbeddedLabelsAnnotations)(nil), (*v1beta1.EmbeddedLabelsAnnotations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_EmbeddedLabelsAnnotations_To_v1beta1_EmbeddedLabelsAnnotations(a.(*EmbeddedLabelsAnnotations), b.(*v1beta1.EmbeddedLabelsAnnotations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.EmbeddedLabelsAnnotations)(nil), (*EmbeddedLabelsAnnotations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EmbeddedLabelsAnnotations_To_v2_EmbeddedLabelsAnnotations(a.(*v1beta1.EmbeddedLabelsAnnotations), b.(*EmbeddedLabelsAnnotations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EmbeddedObjectMeta)(nil), (*v1beta1.EmbeddedObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_EmbeddedObjectMeta_To_v1beta1_EmbeddedObjectMeta(a.(*EmbeddedObjectMeta), b.(*v1beta1.EmbeddedObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.EmbeddedObjectMeta)(nil), (*EmbeddedObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EmbeddedObjectMeta_To_v2_EmbeddedObjectMeta(a.(*v1beta1.EmbeddedObjectMeta), b.(*EmbeddedObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersistentVolumeClaim)(nil), (*v1beta1.PersistentVolumeClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_PersistentVolumeClaim_To_v1beta1_PersistentVolumeClaim(a.(*PersistentVolumeClaim), b.(*v1beta1.PersistentVolumeClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PersistentVolumeClaim)(nil), (*PersistentVolumeClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PersistentVolumeClaim_To_v2_PersistentVolumeClaim(a.(*v1beta1.PersistentVolumeClaim), b.(*PersistentVolumeClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PodTemplateSpec)(nil), (*v1beta1.PodTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_PodTemplateSpec_To_v1beta1_PodTemplateSpec(a.(*PodTemplateSpec), b.(*v1beta1.PodTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PodTemplateSpec)(nil), (*PodTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PodTemplateSpec_To_v2_PodTemplateSpec(a.(*v1beta1.PodTemplateSpec), b.(*PodTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RabbitmqCluster)(nil), (*v1beta1.RabbitmqCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_RabbitmqCluster_To_v1beta1_RabbitmqCluster(a.(*RabbitmqCluster), b.(*v1beta1.RabbitmqCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RabbitmqCluster)(nil), (*RabbitmqCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RabbitmqCluster_To_v2_RabbitmqCluster(a.(*v1beta1.RabbitmqCluster), b.(*RabbitmqCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RabbitmqClusterAdmin)(nil), (*v1beta1.RabbitmqClusterAdmin)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_RabbitmqClusterAdmin_To_v1beta1_RabbitmqClusterAdmin(a.(*RabbitmqClusterAdmin), b.(*v1beta1.RabbitmqClusterAdmin), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RabbitmqClusterAdmin)(nil), (*RabbitmqClusterAdmin)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RabbitmqClusterAdmin_To_v2_RabbitmqClusterAdmin(a.(*v1beta1.RabbitmqClusterAdmin), b.(*RabbitmqClusterAdmin), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RabbitmqClusterConfigurationSpec)(nil), (*v1beta1.RabbitmqClusterConfigurationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_RabbitmqClusterConfigurationSpec_To_v1beta1_RabbitmqClusterConfigurationSpec(a.(*RabbitmqClusterConfigurationSpec), b.(*v1beta1.RabbitmqClusterConfigurationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RabbitmqClusterConfigurationSpec)(nil), (*RabbitmqClusterConfigurationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RabbitmqClusterConfigurationSpec_To_v2_RabbitmqClusterConfigurationSpec(a.(*v1beta1.RabbitmqClusterConfigurationSpec), b.(*RabbitmqClusterConfigurationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RabbitmqClusterList)(nil), (*v1beta1.RabbitmqClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_RabbitmqClusterList_To_v1beta1_RabbitmqClusterList(a.(*RabbitmqClusterList), b.(*v1beta1.RabbitmqClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RabbitmqClusterList)(nil), (*RabbitmqClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RabbitmqClusterList_To_v2_RabbitmqClusterList(a.(*v1beta1.RabbitmqClusterList), b.(*RabbitmqClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RabbitmqClusterOverrideSpec)(nil), (*v1beta1.RabbitmqClusterOverrideSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_RabbitmqClusterOverrideSpec_To_v1beta1_RabbitmqClusterOverrideSpec(a.(*RabbitmqClusterOverrideSpec), b.(*v1beta1.RabbitmqClusterOverrideSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RabbitmqClusterOverrideSpec)(nil), (*RabbitmqClusterOverrideSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RabbitmqClusterOverrideSpec_To_v2_RabbitmqClusterOverrideSpec(a.(*v1beta1.RabbitmqClusterOverrideSpec), b.(*RabbitmqClusterOverrideSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RabbitmqClusterPersistenceSpec)(nil), (*v1beta1.RabbitmqClusterPersistenceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_RabbitmqClusterPersistenceSpec_To_v1beta1_RabbitmqClusterPersistenceSpec(a.(*RabbitmqClusterPersistenceSpec), b.(*v1beta1.RabbitmqClusterPersistenceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RabbitmqClusterPersistenceSpec)(nil), (*RabbitmqClusterPersistenceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RabbitmqClusterPersistenceSpec_To_v2_RabbitmqClusterPersistenceSpec(a.(*v1beta1.RabbitmqClusterPersistenceSpec), b.(*RabbitmqClusterPersistenceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RabbitmqClusterSecretReference)(nil), (*v1beta1.RabbitmqClusterSecretReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_RabbitmqClusterSecretReference_To_v1beta1_RabbitmqClusterSecretReference(a.(*RabbitmqClusterSecretReference), b.(*v1beta1.RabbitmqClusterSecretReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RabbitmqClusterSecretReference)(nil), (*RabbitmqClusterSecretReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RabbitmqClusterSecretReference_To_v2_RabbitmqClusterSecretReference(a.(*v1beta1.RabbitmqClusterSecretReference), b.(*RabbitmqClusterSecretReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RabbitmqClusterServiceReference)(nil), (*v1beta1.RabbitmqClusterServiceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_RabbitmqClusterServiceReference_To_v1beta1_RabbitmqClusterServiceReference(a.(*RabbitmqClusterServiceReference), b.(*v1beta1.RabbitmqClusterServiceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RabbitmqClusterServiceReference)(nil), (*RabbitmqClusterServiceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RabbitmqClusterServiceReference_To_v2_RabbitmqClusterServiceReference(a.(*v1beta1.RabbitmqClusterServiceReference), b.(*RabbitmqClusterServiceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RabbitmqClusterSpec)(nil), (*v1beta1.RabbitmqClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_RabbitmqClusterSpec_To_v1beta1_RabbitmqClusterSpec(a.(*RabbitmqClusterSpec), b.(*v1beta1.RabbitmqClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RabbitmqClusterSpec)(nil), (*RabbitmqClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RabbitmqClusterSpec_To_v2_RabbitmqClusterSpec(a.(*v1beta1.RabbitmqClusterSpec), b.(*RabbitmqClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RabbitmqClusterStatus)(nil), (*v1beta1.RabbitmqClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_RabbitmqClusterStatus_To_v1beta1_RabbitmqClusterStatus(a.(*RabbitmqClusterStatus), b.(*v1beta1.RabbitmqClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RabbitmqClusterStatus)(nil), (*RabbitmqClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RabbitmqClusterStatus_To_v2_RabbitmqClusterStatus(a.(*v1beta1.RabbitmqClusterStatus), b.(*RabbitmqClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StatefulSet)(nil), (*v1beta1.StatefulSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_StatefulSet_To_v1beta1_StatefulSet(a.(*StatefulSet), b.(*v1beta1.StatefulSet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.StatefulSet)(nil), (*StatefulSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_StatefulSet_To_v2_StatefulSet(a.(*v1beta1.StatefulSet), b.(*StatefulSet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StatefulSetSpec)(nil), (*v1beta1.StatefulSetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_StatefulSetSpec_To_v1beta1_StatefulSetSpec(a.(*StatefulSetSpec), b.(*v1beta1.StatefulSetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.StatefulSetSpec)(nil), (*StatefulSetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_StatefulSetSpec_To_v2_StatefulSetSpec(a.(*v1beta1.StatefulSetSpec), b.(*StatefulSetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TLSSpec)(nil), (*v1beta1.TLSSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_TLSSpec_To_v1beta1_TLSSpec(a.(*TLSSpec), b.(*v1beta1.TLSSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TLSSpec)(nil), (*TLSSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TLSSpec_To_v2_TLSSpec(a.(*v1beta1.TLSSpec), b.(*TLSSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v2_ClientService_To_v1beta1_ClientService(in *ClientService, out *v1beta1.ClientService, s conversion.Scope) error {
	out.EmbeddedLabelsAnnotations = (*v1beta1.EmbeddedLabelsAnnotations)(unsafe.Pointer(in.EmbeddedLabelsAnnotations))
	out.Spec = (*v1.ServiceSpec)(unsafe.Pointer(in.Spec))
	return nil
}

// Convert_v2_ClientService_To_v1beta1_ClientService is an autogenerated conversion function.
func Convert_v2_ClientService_To_v1beta1_ClientService(in *ClientService, out *v1beta1.ClientService, s conversion.Scope) error {
	return autoConvert_v2_ClientService_To_v1beta1_ClientService(in, out, s)
}

func autoConvert_v1beta1_ClientService_To_v2_ClientService(in *v1beta1.ClientService, out *ClientService, s conversion.Scope) error {
	out.EmbeddedLabelsAnnotations = (*EmbeddedLabelsAnnotations)(unsafe.Pointer(in.EmbeddedLabelsAnnotations))
	out.Spec = (*v1.ServiceSpec)(unsafe.Pointer(in.Spec))
	return nil
}

// Convert_v1beta1_ClientService_To_v2_ClientService is an autogenerated conversion function.
func Convert_v1beta1_ClientService_To_v2_ClientService(in *v1beta1.ClientService, out *ClientService, s conversion.Scope) error {
	return autoConvert_v1beta1_ClientService_To_v2_ClientService(in, out, s)
}

func autoConvert_v2_EmbeddedLabelsAnnotations_To_v1beta1_EmbeddedLabelsAnnotations(in *EmbeddedLabelsAnnotations, out *v1beta1.EmbeddedLabelsAnnotations, s conversion.Scope) error {
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_v2_EmbeddedLabelsAnnotations_To_v1beta1_EmbeddedLabelsAnnotations is an autogenerated conversion function.
func Convert_v2_EmbeddedLabelsAnnotations_To_v1beta1_EmbeddedLabelsAnnotations(in *EmbeddedLabelsAnnotations, out *v1beta1.EmbeddedLabelsAnnotations, s conversion.Scope) error {
	return autoConvert_v2_EmbeddedLabelsAnnotations_To_v1beta1_EmbeddedLabelsAnnotations(in, out, s)
}

func autoConvert_v1beta1_EmbeddedLabelsAnnotations_To_v2_EmbeddedLabelsAnnotations(in *v1beta1.EmbeddedLabelsAnnotations, out *EmbeddedLabelsAnnotations, s conversion.Scope) error {
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_v1beta1_EmbeddedLabelsAnnotations_To_v2_EmbeddedLabelsAnnotations is an autogenerated conversion function.
func Convert_v1beta1_EmbeddedLabelsAnnotations_To_v2_EmbeddedLabelsAnnotations(in *v1beta1.EmbeddedLabelsAnnotations, out *EmbeddedLabelsAnnotations, s conversion.Scope) error {
	return autoConvert_v1beta1_EmbeddedLabelsAnnotations_To_v2_EmbeddedLabelsAnnotations(in, out, s)
}

func autoConvert_v2_EmbeddedObjectMeta_To_v1beta1_EmbeddedObjectMeta(in *EmbeddedObjectMeta, out *v1beta1.EmbeddedObjectMeta, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_v2_EmbeddedObjectMeta_To_v1beta1_EmbeddedObjectMeta is an autogenerated conversion function.
func Convert_v2_EmbeddedObjectMeta_To_v1beta1_EmbeddedObjectMeta(in *EmbeddedObjectMeta, out *v1beta1.EmbeddedObjectMeta, s conversion.Scope) error {
	return autoConvert_v2_EmbeddedObjectMeta_To_v1beta1_EmbeddedObjectMeta(in, out, s)
}

func autoConvert_v1beta1_EmbeddedObjectMeta_To_v2_EmbeddedObjectMeta(in *v1beta1.EmbeddedObjectMeta, out *EmbeddedObjectMeta, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_v1beta1_EmbeddedObjectMeta_To_v2_EmbeddedObjectMeta is an autogenerated conversion function.
func Convert_v1beta1_EmbeddedObjectMeta_To_v2_EmbeddedObjectMeta(in *v1beta1.EmbeddedObjectMeta, out *EmbeddedObjectMeta, s conversion.Scope) error {
	return autoConvert_v1beta1_EmbeddedObjectMeta_To_v2_EmbeddedObjectMeta(in, out, s)
}

func autoConvert_v2_PersistentVolumeClaim_To_v1beta1_PersistentVolumeClaim(in *PersistentVolumeClaim, out *v1beta1.PersistentVolumeClaim, s conversion.Scope) error {
	if err := Convert_v2_EmbeddedObjectMeta_To_v1beta1_EmbeddedObjectMeta(&in.EmbeddedObjectMeta, &out.EmbeddedObjectMeta, s); err != nil {
		return err
	}
	out.Spec = in.Spec
	return nil
}

// Convert_v2_PersistentVolumeClaim_To_v1beta1_PersistentVolumeClaim is an autogenerated conversion function.
func Convert_v2_PersistentVolumeClaim_To_v1beta1_PersistentVolumeClaim(in *PersistentVolumeClaim, out *v1beta1.PersistentVolumeClaim, s conversion.Scope) error {
	return autoConvert_v2_PersistentVolumeClaim_To_v1beta1_PersistentVolumeClaim(in, out, s)
}

func autoConvert_v1beta1_PersistentVolumeClaim_To_v2_PersistentVolumeClaim(in *v1beta1.PersistentVolumeClaim, out *PersistentVolumeClaim, s conversion.Scope) error {
	if err := Convert_v1beta1_EmbeddedObjectMeta_To_v2_EmbeddedObjectMeta(&in.EmbeddedObjectMeta, &out.EmbeddedObjectMeta, s); err != nil {
		return err
	}
	out.Spec = in.Spec
	return nil
}

// Convert_v1beta1_PersistentVolumeClaim_To_v2_PersistentVolumeClaim is an autogenerated conversion function.
func Convert_v1beta1_PersistentVolumeClaim_To_v2_PersistentVolumeClaim(in *v1beta1.PersistentVolumeClaim, out *PersistentVolumeClaim, s conversion.Scope) error {
	return autoConvert_v1beta1_PersistentVolumeClaim_To_v2_PersistentVolumeClaim(in, out, s)
}

func autoConvert_v2_PodTemplateSpec_To_v1beta1_PodTemplateSpec(in *PodTemplateSpec, out *v1beta1.PodTemplateSpec, s conversion.Scope) error {
	out.EmbeddedObjectMeta = (*v1beta1.EmbeddedObjectMeta)(unsafe.Pointer(in.EmbeddedObjectMeta))
	out.Spec = (*v1.PodSpec)(unsafe.Pointer(in.Spec))
	return nil
}

// Convert_v2_PodTemplateSpec_To_v1beta1_PodTemplateSpec is an autogenerated conversion function.
func Convert_v2_PodTemplateSpec_To_v1beta1_PodTemplateSpec(in *PodTemplateSpec, out *v1beta1.PodTemplateSpec, s conversion.Scope) error {
	return autoConvert_v2_PodTemplateSpec_To_v1beta1_PodTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_PodTemplateSpec_To_v2_PodTemplateSpec(in *v1beta1.PodTemplateSpec, out *PodTemplateSpec, s conversion.Scope) error {
	out.EmbeddedObjectMeta = (*EmbeddedObjectMeta)(unsafe.Pointer(in.EmbeddedObjectMeta))
	out.Spec = (*v1.PodSpec)(unsafe.Pointer(in.Spec))
	return nil
}

// Convert_v1beta1_PodTemplateSpec_To_v2_PodTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_PodTemplateSpec_To_v2_PodTemplateSpec(in *v1beta1.PodTemplateSpec, out *PodTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_PodTemplateSpec_To_v2_PodTemplateSpec(in, out, s)
}

func autoConvert_v2_RabbitmqCluster_To_v1beta1_RabbitmqCluster(in *RabbitmqCluster, out *v1beta1.RabbitmqCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v2_RabbitmqClusterSpec_To_v1beta1_RabbitmqClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v2_RabbitmqClusterStatus_To_v1beta1_RabbitmqClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v2_RabbitmqCluster_To_v1beta1_RabbitmqCluster is an autogenerated conversion function.
func Convert_v2_RabbitmqCluster_To_v1beta1_RabbitmqCluster(in *RabbitmqCluster, out *v1beta1.RabbitmqCluster, s conversion.Scope) error {
	return autoConvert_v2_RabbitmqCluster_To_v1beta1_RabbitmqCluster(in, out, s)
}

func autoConvert_v1beta1_RabbitmqCluster_To_v2_RabbitmqCluster(in *v1beta1.RabbitmqCluster, out *RabbitmqCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_RabbitmqClusterSpec_To_v2_RabbitmqClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RabbitmqClusterStatus_To_v2_RabbitmqClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RabbitmqCluster_To_v2_RabbitmqCluster is an autogenerated conversion function.
func Convert_v1beta1_RabbitmqCluster_To_v2_RabbitmqCluster(in *v1beta1.RabbitmqCluster, out *RabbitmqCluster, s conversion.Scope) error {
	return autoConvert_v1beta1_RabbitmqCluster_To_v2_RabbitmqCluster(in, out, s)
}

func autoConvert_v2_RabbitmqClusterAdmin_To_v1beta1_RabbitmqClusterAdmin(in *RabbitmqClusterAdmin, out *v1beta1.RabbitmqClusterAdmin, s conversion.Scope) error {
	out.SecretReference = (*v1beta1.RabbitmqClusterSecretReference)(unsafe.Pointer(in.SecretReference))
	out.ServiceReference = (*v1beta1.RabbitmqClusterServiceReference)(unsafe.Pointer(in.ServiceReference))
	return nil
}

// Convert_v2_RabbitmqClusterAdmin_To_v1beta1_RabbitmqClusterAdmin is an autogenerated conversion function.
func Convert_v2_RabbitmqClusterAdmin_To_v1beta1_RabbitmqClusterAdmin(in *RabbitmqClusterAdmin, out *v1beta1.RabbitmqClusterAdmin, s conversion.Scope) error {
	return autoConvert_v2_RabbitmqClusterAdmin_To_v1beta1_RabbitmqClusterAdmin(in, out, s)
}

func autoConvert_v1beta1_RabbitmqClusterAdmin_To_v2_RabbitmqClusterAdmin(in *v1beta1.RabbitmqClusterAdmin, out *RabbitmqClusterAdmin, s conversion.Scope) error {
	out.SecretReference = (*RabbitmqClusterSecretReference)(unsafe.Pointer(in.SecretReference))
	out.ServiceReference = (*RabbitmqClusterServiceReference)(unsafe.Pointer(in.ServiceReference))
	return nil
}

// Convert_v1beta1_RabbitmqClusterAdmin_To_v2_RabbitmqClusterAdmin is an autogenerated conversion function.
func Convert_v1beta1_RabbitmqClusterAdmin_To_v2_RabbitmqClusterAdmin(in *v1beta1.RabbitmqClusterAdmin, out *RabbitmqClusterAdmin, s conversion.Scope) error {
	return autoConvert_v1beta1_RabbitmqClusterAdmin_To_v2_RabbitmqClusterAdmin(in, out, s)
}

func autoConvert_v2_RabbitmqClusterConfigurationSpec_To_v1beta1_RabbitmqClusterConfigurationSpec(in *RabbitmqClusterConfigurationSpec, out *v1beta1.RabbitmqClusterConfigurationSpec, s conversion.Scope) error {
	out.AdditionalPlugins = *(*[]v1beta1.Plugin)(unsafe.Pointer(&in.AdditionalPlugins))
	out.AdditionalConfig = in.AdditionalConfig
	out.AdvancedConfig = in.AdvancedConfig
	out.EnvConfig = in.EnvConfig
	return nil
}

// Convert_v2_RabbitmqClusterConfigurationSpec_To_v1beta1_RabbitmqClusterConfigurationSpec is an autogenerated conversion function.
func Convert_v2_RabbitmqClusterConfigurationSpec_To_v1beta1_RabbitmqClusterConfigurationSpec(in *RabbitmqClusterConfigurationSpec, out *v1beta1.RabbitmqClusterConfigurationSpec, s conversion.Scope) error {
	return autoConvert_v2_RabbitmqClusterConfigurationSpec_To_v1beta1_RabbitmqClusterConfigurationSpec(in, out, s)
}

func autoConvert_v1beta1_RabbitmqClusterConfigurationSpec_To_v2_RabbitmqClusterConfigurationSpec(in *v1beta1.RabbitmqClusterConfigurationSpec, out *RabbitmqClusterConfigurationSpec, s conversion.Scope) error {
	out.AdditionalPlugins = *(*[]Plugin)(unsafe.Pointer(&in.AdditionalPlugins))
	out.AdditionalConfig = in.AdditionalConfig
	out.AdvancedConfig = in.AdvancedConfig
	out.EnvConfig = in.EnvConfig
	return nil
}

// Convert_v1beta1_RabbitmqClusterConfigurationSpec_To_v2_RabbitmqClusterConfigurationSpec is an autogenerated conversion function.
func Convert_v1beta1_RabbitmqClusterConfigurationSpec_To_v2_RabbitmqClusterConfigurationSpec(in *v1beta1.RabbitmqClusterConfigurationSpec, out *RabbitmqClusterConfigurationSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RabbitmqClusterConfigurationSpec_To_v2_RabbitmqClusterConfigurationSpec(in, out, s)
}

func autoConvert_v2_RabbitmqClusterList_To_v1beta1_RabbitmqClusterList(in *RabbitmqClusterList, out *v1beta1.RabbitmqClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.RabbitmqCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v2_RabbitmqClusterList_To_v1beta1_RabbitmqClusterList is an autogenerated conversion function.
func Convert_v2_RabbitmqClusterList_To_v1beta1_RabbitmqClusterList(in *RabbitmqClusterList, out *v1beta1.RabbitmqClusterList, s conversion.Scope) error {
	return autoConvert_v2_RabbitmqClusterList_To_v1beta1_RabbitmqClusterList(in, out, s)
}

func autoConvert_v1beta1_RabbitmqClusterList_To_v2_RabbitmqClusterList(in *v1beta1.RabbitmqClusterList, out *RabbitmqClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]RabbitmqCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_RabbitmqClusterList_To_v2_RabbitmqClusterList is an autogenerated conversion function.
func Convert_v1beta1_RabbitmqClusterList_To_v2_RabbitmqClusterList(in *v1beta1.RabbitmqClusterList, out *RabbitmqClusterList, s conversion.Scope) error {
	return autoConvert_v1beta1_RabbitmqClusterList_To_v2_RabbitmqClusterList(in, out, s)
}

func autoConvert_v2_RabbitmqClusterOverrideSpec_To_v1beta1_RabbitmqClusterOverrideSpec(in *RabbitmqClusterOverrideSpec, out *v1beta1.RabbitmqClusterOverrideSpec, s conversion.Scope) error {
	out.StatefulSet = (*v1beta1.StatefulSet)(unsafe.Pointer(in.StatefulSet))
	out.ClientService = (*v1beta1.ClientService)(unsafe.Pointer(in.ClientService))
	return nil
}

// Convert_v2_RabbitmqClusterOverrideSpec_To_v1beta1_RabbitmqClusterOverrideSpec is an autogenerated conversion function.
func Convert_v2_RabbitmqClusterOverrideSpec_To_v1beta1_RabbitmqClusterOverrideSpec(in *RabbitmqClusterOverrideSpec, out *v1beta1.RabbitmqClusterOverrideSpec, s conversion.Scope) error {
	return autoConvert_v2_RabbitmqClusterOverrideSpec_To_v1beta1_RabbitmqClusterOverrideSpec(in, out, s)
}

func autoConvert_v1beta1_RabbitmqClusterOverrideSpec_To_v2_RabbitmqClusterOverrideSpec(in *v1beta1.RabbitmqClusterOverrideSpec, out *RabbitmqClusterOverrideSpec, s conversion.Scope) error {
	out.StatefulSet = (*StatefulSet)(unsafe.Pointer(in.StatefulSet))
	out.ClientService = (*ClientService)(unsafe.Pointer(in.ClientService))
	return nil
}

// Convert_v1beta1_RabbitmqClusterOverrideSpec_To_v2_RabbitmqClusterOverrideSpec is an autogenerated conversion function.
func Convert_v1beta1_RabbitmqClusterOverrideSpec_To_v2_RabbitmqClusterOverrideSpec(in *v1beta1.RabbitmqClusterOverrideSpec, out *RabbitmqClusterOverrideSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RabbitmqClusterOverrideSpec_To_v2_RabbitmqClusterOverrideSpec(in, out, s)
}

func autoConvert_v2_RabbitmqClusterPersistenceSpec_To_v1beta1_RabbitmqClusterPersistenceSpec(in *RabbitmqClusterPersistenceSpec, out *v1beta1.RabbitmqClusterPersistenceSpec, s conversion.Scope) error {
	out.StorageClassName = (*string)(unsafe.Pointer(in.StorageClassName))
	out.Storage = (*resource.Quantity)(unsafe.Pointer(in.Storage))
	return nil
}

// Convert_v2_RabbitmqClusterPersistenceSpec_To_v1beta1_RabbitmqClusterPersistenceSpec is an autogenerated conversion function.
func Convert_v2_RabbitmqClusterPersistenceSpec_To_v1beta1_RabbitmqClusterPersistenceSpec(in *RabbitmqClusterPersistenceSpec, out *v1beta1.RabbitmqClusterPersistenceSpec, s conversion.Scope) error {
	return autoConvert_v2_RabbitmqClusterPersistenceSpec_To_v1beta1_RabbitmqClusterPersistenceSpec(in, out, s)
}

func autoConvert_v1beta1_RabbitmqClusterPersistenceSpec_To_v2_RabbitmqClusterPersistenceSpec(in *v1beta1.RabbitmqClusterPersistenceSpec, out *RabbitmqClusterPersistenceSpec, s conversion.Scope) error {
	out.StorageClassName = (*string)(unsafe.Pointer(in.StorageClassName))
	out.Storage = (*resource.Quantity)(unsafe.Pointer(in.Storage))
	return nil
}

// Convert_v1beta1_RabbitmqClusterPersistenceSpec_To_v2_RabbitmqClusterPersistenceSpec is an autogenerated conversion function.
func Convert_v1beta1_RabbitmqClusterPersistenceSpec_To_v2_RabbitmqClusterPersistenceSpec(in *v1beta1.RabbitmqClusterPersistenceSpec, out *RabbitmqClusterPersistenceSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RabbitmqClusterPersistenceSpec_To_v2_RabbitmqClusterPersistenceSpec(in, out, s)
}

func autoConvert_v2_RabbitmqClusterSecretReference_To_v1beta1_RabbitmqClusterSecretReference(in *RabbitmqClusterSecretReference, out *v1beta1.RabbitmqClusterSecretReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Keys = *(*map[string]string)(unsafe.Pointer(&in.Keys))
	return nil
}

// Convert_v2_RabbitmqClusterSecretReference_To_v1beta1_RabbitmqClusterSecretReference is an autogenerated conversion function.
func Convert_v2_RabbitmqClusterSecretReference_To_v1beta1_RabbitmqClusterSecretReference(in *RabbitmqClusterSecretReference, out *v1beta1.RabbitmqClusterSecretReference, s conversion.Scope) error {
	return autoConvert_v2_RabbitmqClusterSecretReference_To_v1beta1_RabbitmqClusterSecretReference(in, out, s)
}

func autoConvert_v1beta1_RabbitmqClusterSecretReference_To_v2_RabbitmqClusterSecretReference(in *v1beta1.RabbitmqClusterSecretReference, out *RabbitmqClusterSecretReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Keys = *(*map[string]string)(unsafe.Pointer(&in.Keys))
	return nil
}

// Convert_v1beta1_RabbitmqClusterSecretReference_To_v2_RabbitmqClusterSecretReference is an autogenerated conversion function.
func Convert_v1beta1_RabbitmqClusterSecretReference_To_v2_RabbitmqClusterSecretReference(in *v1beta1.RabbitmqClusterSecretReference, out *RabbitmqClusterSecretReference, s conversion.Scope) error {
	return autoConvert_v1beta1_RabbitmqClusterSecretReference_To_v2_RabbitmqClusterSecretReference(in, out, s)
}

func autoConvert_v2_RabbitmqClusterServiceReference_To_v1beta1_RabbitmqClusterServiceReference(in *RabbitmqClusterServiceReference, out *v1beta1.RabbitmqClusterServiceReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v2_RabbitmqClusterServiceReference_To_v1beta1_RabbitmqClusterServiceReference is an autogenerated conversion function.
func Convert_v2_RabbitmqClusterServiceReference_To_v1beta1_RabbitmqClusterServiceReference(in *RabbitmqClusterServiceReference, out *v1beta1.RabbitmqClusterServiceReference, s conversion.Scope) error {
	return autoConvert_v2_RabbitmqClusterServiceReference_To_v1beta1_RabbitmqClusterServiceReference(in, out, s)
}

func autoConvert_v1beta1_RabbitmqClusterServiceReference_To_v2_RabbitmqClusterServiceReference(in *v1beta1.RabbitmqClusterServiceReference, out *RabbitmqClusterServiceReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1beta1_RabbitmqClusterServiceReference_To_v2_RabbitmqClusterServiceReference is an autogenerated conversion function.
func Convert_v1beta1_RabbitmqClusterServiceReference_To_v2_RabbitmqClusterServiceReference(in *v1beta1.RabbitmqClusterServiceReference, out *RabbitmqClusterServiceReference, s conversion.Scope) error {
	return autoConvert_v1beta1_RabbitmqClusterServiceReference_To_v2_RabbitmqClusterServiceReference(in, out, s)
}

func autoConvert_v2_RabbitmqClusterSpec_To_v1beta1_RabbitmqClusterSpec(in *RabbitmqClusterSpec, out *v1beta1.RabbitmqClusterSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Image = in.Image
	out.ImagePullSecret = in.ImagePullSecret
	// INFO: in.ClientService opted out of conversion generation
	if err := Convert_v2_RabbitmqClusterPersistenceSpec_To_v1beta1_RabbitmqClusterPersistenceSpec(&in.Persistence, &out.Persistence, s); err != nil {
		return err
	}
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.Affinity = (*v1.Affinity)(unsafe.Pointer(in.Affinity))
	out.Tolerations = *(*[]v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	if err := Convert_v2_RabbitmqClusterConfigurationSpec_To_v1beta1_RabbitmqClusterConfigurationSpec(&in.Rabbitmq, &out.Rabbitmq, s); err != nil {
		return err
	}
	if err := Convert_v2_TLSSpec_To_v1beta1_TLSSpec(&in.TLS, &out.TLS, s); err != nil {
		return err
	}
	if err := Convert_v2_RabbitmqClusterOverrideSpec_To_v1beta1_RabbitmqClusterOverrideSpec(&in.Override, &out.Override, s); err != nil {
		return err
	}
	return nil
}

// Convert_v2_RabbitmqClusterSpec_To_v1beta1_RabbitmqClusterSpec is an autogenerated conversion function.
func Convert_v2_RabbitmqClusterSpec_To_v1beta1_RabbitmqClusterSpec(in *RabbitmqClusterSpec, out *v1beta1.RabbitmqClusterSpec, s conversion.Scope) error {
	return autoConvert_v2_RabbitmqClusterSpec_To_v1beta1_RabbitmqClusterSpec(in, out, s)
}

func autoConvert_v1beta1_RabbitmqClusterSpec_To_v2_RabbitmqClusterSpec(in *v1beta1.RabbitmqClusterSpec, out *RabbitmqClusterSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Image = in.Image
	out.ImagePullSecret = in.ImagePullSecret
	// INFO: in.Service opted out of conversion generation
	if err := Convert_v1beta1_RabbitmqClusterPersistenceSpec_To_v2_RabbitmqClusterPersistenceSpec(&in.Persistence, &out.Persistence, s); err != nil {
		return err
	}
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.Affinity = (*v1.Affinity)(unsafe.Pointer(in.Affinity))
	out.Tolerations = *(*[]v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	if err := Convert_v1beta1_RabbitmqClusterConfigurationSpec_To_v2_RabbitmqClusterConfigurationSpec(&in.Rabbitmq, &out.Rabbitmq, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_TLSSpec_To_v2_TLSSpec(&in.TLS, &out.TLS, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RabbitmqClusterOverrideSpec_To_v2_RabbitmqClusterOverrideSpec(&in.Override, &out.Override, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RabbitmqClusterSpec_To_v2_RabbitmqClusterSpec is an autogenerated conversion function.
func Convert_v1beta1_RabbitmqClusterSpec_To_v2_RabbitmqClusterSpec(in *v1beta1.RabbitmqClusterSpec, out *RabbitmqClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RabbitmqClusterSpec_To_v2_RabbitmqClusterSpec(in, out, s)
}

func autoConvert_v2_RabbitmqClusterStatus_To_v1beta1_RabbitmqClusterStatus(in *RabbitmqClusterStatus, out *v1beta1.RabbitmqClusterStatus, s conversion.Scope) error {
	out.ClusterStatus = in.ClusterStatus
	out.Conditions = *(*[]status.RabbitmqClusterCondition)(unsafe.Pointer(&in.Conditions))
	out.Admin = (*v1beta1.RabbitmqClusterAdmin)(unsafe.Pointer(in.Admin))
	return nil
}

// Convert_v2_RabbitmqClusterStatus_To_v1beta1_RabbitmqClusterStatus is an autogenerated conversion function.
func Convert_v2_RabbitmqClusterStatus_To_v1beta1_RabbitmqClusterStatus(in *RabbitmqClusterStatus, out *v1beta1.RabbitmqClusterStatus, s conversion.Scope) error {
	return autoConvert_v2_RabbitmqClusterStatus_To_v1beta1_RabbitmqClusterStatus(in, out, s)
}

func autoConvert_v1beta1_RabbitmqClusterStatus_To_v2_RabbitmqClusterStatus(in *v1beta1.RabbitmqClusterStatus, out *RabbitmqClusterStatus, s conversion.Scope) error {
	out.ClusterStatus = in.ClusterStatus
	out.Conditions = *(*[]status.RabbitmqClusterCondition)(unsafe.Pointer(&in.Conditions))
	out.Admin = (*RabbitmqClusterAdmin)(unsafe.Pointer(in.Admin))
	return nil
}

// Convert_v1beta1_RabbitmqClusterStatus_To_v2_RabbitmqClusterStatus is an autogenerated conversion function.
func Convert_v1beta1_RabbitmqClusterStatus_To_v2_RabbitmqClusterStatus(in *v1beta1.RabbitmqClusterStatus, out *RabbitmqClusterStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_RabbitmqClusterStatus_To_v2_RabbitmqClusterStatus(in, out, s)
}

func autoConvert_v2_StatefulSet_To_v1beta1_StatefulSet(in *StatefulSet, out *v1beta1.StatefulSet, s conversion.Scope) error {
	out.EmbeddedLabelsAnnotations = (*v1beta1.EmbeddedLabelsAnnotations)(unsafe.Pointer(in.EmbeddedLabelsAnnotations))
	out.Spec = (*v1beta1.StatefulSetSpec)(unsafe.Pointer(in.Spec))
	return nil
}

// Convert_v2_StatefulSet_To_v1beta1_StatefulSet is an autogenerated conversion function.
func Convert_v2_StatefulSet_To_v1beta1_StatefulSet(in *StatefulSet, out *v1beta1.StatefulSet, s conversion.Scope) error {
	return autoConvert_v2_StatefulSet_To_v1beta1_StatefulSet(in, out, s)
}

func autoConvert_v1beta1_StatefulSet_To_v2_StatefulSet(in *v1beta1.StatefulSet, out *StatefulSet, s conversion.Scope) error {
	out.EmbeddedLabelsAnnotations = (*EmbeddedLabelsAnnotations)(unsafe.Pointer(in.EmbeddedLabelsAnnotations))
	out.Spec = (*StatefulSetSpec)(unsafe.Pointer(in.Spec))
	return nil
}

// Convert_v1beta1_StatefulSet_To_v2_StatefulSet is an autogenerated conversion function.
func Convert_v1beta1_StatefulSet_To_v2_StatefulSet(in *v1beta1.StatefulSet, out *StatefulSet, s conversion.Scope) error {
	return autoConvert_v1beta1_StatefulSet_To_v2_StatefulSet(in, out, s)
}

func autoConvert_v2_StatefulSetSpec_To_v1beta1_StatefulSetSpec(in *StatefulSetSpec, out *v1beta1.StatefulSetSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Selector = (*metav1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.Template = (*v1beta1.PodTemplateSpec)(unsafe.Pointer(in.Template))
	out.VolumeClaimTemplates = *(*[]v1beta1.PersistentVolumeClaim)(unsafe.Pointer(&in.VolumeClaimTemplates))
	out.ServiceName = in.ServiceName
	out.PodManagementPolicy = appsv1.PodManagementPolicyType(in.PodManagementPolicy)
	out.UpdateStrategy = (*appsv1.StatefulSetUpdateStrategy)(unsafe.Pointer(in.UpdateStrategy))
	return nil
}

// Convert_v2_StatefulSetSpec_To_v1beta1_StatefulSetSpec is an autogenerated conversion function.
func Convert_v2_StatefulSetSpec_To_v1beta1_StatefulSetSpec(in *StatefulSetSpec, out *v1beta1.StatefulSetSpec, s conversion.Scope) error {
	return autoConvert_v2_StatefulSetSpec_To_v1beta1_StatefulSetSpec(in, out, s)
}

func autoConvert_v1beta1_StatefulSetSpec_To_v2_StatefulSetSpec(in *v1beta1.StatefulSetSpec, out *StatefulSetSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Selector = (*metav1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.Template = (*PodTemplateSpec)(unsafe.Pointer(in.Template))
	out.VolumeClaimTemplates = *(*[]PersistentVolumeClaim)(unsafe.Pointer(&in.VolumeClaimTemplates))
	out.ServiceName = in.ServiceName
	out.PodManagementPolicy = appsv1.PodManagementPolicyType(in.PodManagementPolicy)
	out.UpdateStrategy = (*appsv1.StatefulSetUpdateStrategy)(unsafe.Pointer(in.UpdateStrategy))
	return nil
}

// Convert_v1beta1_StatefulSetSpec_To_v2_StatefulSetSpec is an autogenerated conversion function.
func Convert_v1beta1_StatefulSetSpec_To_v2_StatefulSetSpec(in *v1beta1.StatefulSetSpec, out *StatefulSetSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_StatefulSetSpec_To_v2_StatefulSetSpec(in, out, s)
}

func autoConvert_v2_TLSSpec_To_v1beta1_TLSSpec(in *TLSSpec, out *v1beta1.TLSSpec, s conversion.Scope) error {
	out.SecretName = in.SecretName
	out.CaSecretName = in.CaSecretName
	out.CaCertName = in.CaCertName
	return nil
}

// Convert_v2_TLSSpec_To_v1beta1_TLSSpec is an autogenerated conversion function.
func Convert_v2_TLSSpec_To_v1beta1_TLSSpec(in *TLSSpec, out *v1beta1.TLSSpec, s conversion.Scope) error {
	return autoConvert_v2_TLSSpec_To_v1beta1_TLSSpec(in, out, s)
}

func autoConvert_v1beta1_TLSSpec_To_v2_TLSSpec(in *v1beta1.TLSSpec, out *TLSSpec, s conversion.Scope) error {
	out.SecretName = in.SecretName
	out.CaSecretName = in.CaSecretName
	out.CaCertName = in.CaCertName
	return nil
}

// Convert_v1beta1_TLSSpec_To_v2_TLSSpec is an autogenerated conversion function.
func Convert_v1beta1_TLSSpec_To_v2_TLSSpec(in *v1beta1.TLSSpec, out *TLSSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_TLSSpec_To_v2_TLSSpec(in, out, s)
}
